"""Добавлена таблица для фотографий мебели

Revision ID: 1fa9587fd431
Revises: c8198310a68b
Create Date: 2025-10-09 00:43:25.507498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fa9587fd431'
down_revision: Union[str, Sequence[str], None] = 'c8198310a68b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('furniture_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('furniture_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['furniture_id'], ['furniture.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_furniture_photos_id'), 'furniture_photos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_furniture_photos_id'), table_name='furniture_photos')
    op.drop_table('furniture_photos')
    # ### end Alembic commands ###
