"""Выпуск бота к продакшену!

Revision ID: 546cf3ac166b
Revises: 57bc17bccbaf
Create Date: 2025-10-11 02:54:36.513181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '546cf3ac166b'
down_revision: Union[str, Sequence[str], None] = '57bc17bccbaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
